name: Build and Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Change this to your default branch if it's not 'main'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'  # Use the Node.js version that matches your development environment

    - name: Install Dependencies
      run: npm install

    - name: Build Ionic App
      run: npm run build -- --prod  # Adjust if your build command differs

    - name: Deploy to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@4.1.4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        branch: gh-pages  # The branch the action should deploy to
        folder: dist  # The folder the action should deploy; adjust if your output directory is different
        clean: true
